# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchReport',
            fields=[
                ('id_kipi', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=2048)),
                ('reference', models.CharField(max_length=512)),
                ('summary', models.CharField(max_length=51200)),
            ],
        ),
    ]
